### ISSUE TITLE
Error reporting: comparison of actual bag contents against standard bag structure

### ISSUE THREAD

**Issue by jwts24** [RockefellerArchiveCenter/digitized_av_validation#14]
## Incomplete picture of invalid bag structure
Due to the sequence of bag structure validation, the validation script will report an error at the first instance of nonconformity, stopping there. The reported error will not necessarily indicate all nonconforming bag elements, for example, (1) when there are multiple missing elements in a bag, or (2) when media files are nested in a folder within the parent data directory, leading the system to think necessary elements are missing. Either of these two scenarios could result in the same error message (“[Master/Mezzanine/Access] file missing”), which doesn’t always provide a precise and complete description of what’s wrong with the bag.

## Mapping bag contents
In order to provide a fuller picture, the system could generate an error message which maps the entire contents of the bag and presents this alongside the expected bag structure. 

## Examples
A video bag missing both master and mezzanine files yields an error message “Master file missing” but does not indicate that the mezzanine file is also absent.
<img width="926" alt="Screenshot 2023-08-25 at 3 17 42 PM" src="https://github.com/RockefellerArchiveCenter/digitized_av_validation/assets/143211472/61465241-a50f-4917-adb3-93e1a5a69e83">

An audio bag with all necessary elements but invalid folder hierarchy still yielded an error message “Master file missing” instead of indicating that the audio files are misplaced in a child folder of the data directory.
<img width="926" alt="Screenshot 2023-08-25 at 3 12 34 PM" src="https://github.com/RockefellerArchiveCenter/digitized_av_validation/assets/143211472/a3a48301-1787-4595-a486-881da14e65a7">

**Comment by helrond** [comment]
@jwts24 give this another shot - I made some updates which should give you a fuller picture of what's going on in the bag payload directory.

**Comment by jwts24** [comment]
@helrond Thank you! I now see the Digitized AV Notification reports back actual files vs. expected files. I've tested this for both cases mentioned above: multiple missing files and nonstandard folder hierarchy.
