### ISSUE TITLE
Error reporting: traceback

### ISSUE THREAD

**Issue by jwts24** [RockefellerArchiveCenter/digitized_av_validation#15]
## Python traceback is read bottom to top
When some validation errors occur, the system will generate traceback to allow the programmer to pinpoint where along the pipeline the error occurred. Traceback contains a lot of useful information, but may not be intuitive to the average user. This is partly because traceback is written with the most recent call last, requiring the user to read it bottom to top. The error message presents the technical details first, burying the error statement. 

## Insert error summary above traceback
To make more apparent the cause of the error, the system could present error messages in a different format, leading with a concise error summary and following with the traceback. 

## Example
This error message involving an already-existing RefID in the QC bucket is presented using conventional traceback, with the most recent call last.
<img width="926" alt="Screenshot 2023-08-25 at 4 04 27 PM" src="https://github.com/RockefellerArchiveCenter/digitized_av_validation/assets/143211472/d06fe5ad-6c58-40ee-bbc7-742c134118fe">

**Comment by helrond** [comment]
@jwts24 This should be fixed now. Give it another shot and, if everything looks okay, then you can just close this issue.

**Comment by jwts24** [comment]
@helrond Looks good! I now see the error statement included above the traceback which makes it more apparent.
