### ISSUE TITLE
Multiple master files for two-sided audio tapes

### ISSUE THREAD

**Issue by jwts24** [RockefellerArchiveCenter/digitized_av_validation#19]
## Bag structure validation fails with multi-file audio masters
Digitizing two-sided audio tapes will result in packages containing discrete A and B master WAV files. This poses an issue for bag structure validation because the system is checking that bags contain only one master file. In addition, the error message generated will say “Master file missing” when, in fact, the issue is that there are two master files. 

## To reproduce
1. Bag and tarball files for a two-sided audio tape (this package should contain multiple master files)
2. Upload the bag to the S3 bucket
3. Await Digitized AV Notification in Microsoft Teams
4. View error message

## Expected behavior
Bag structure validation failure. Error message should read, “Audio package is invalid. Master file missing.”

## Screenshot
![image](https://github.com/RockefellerArchiveCenter/digitized_av_validation/assets/143211472/d42fe801-888e-4b8a-9972-add3f4c6ff4a)

## Impact on your work
The fact that two-sided tape transfers do not conform to the presently-defined standards for bag structure validation makes it impossible to pass these packages through the digital infrastructure for access and long-term storage. 

## Additional context
A solution will have to take into account file naming conventions and how to work around file suffixes (i.e., [RefID]A, [RefID]B) in order to cross-reference RefIDs with ArchivesSpace.

**Comment by helrond** [comment]
Thanks @jwts24! Just to double check: If a package has multiple master files, would we expect it to have the same number of access files, or will there always only be one access file? As you've described the issue above there would only be one access file but I want to be sure!

**Comment by jwts24** [comment]
Good question @helrond! When there are multiple master files, there could be one rendered audio file, but it is also possible that there could be multiple rendered audio files. For example, if the content is seven hours, the access element may be separated into two or more access files. I will adjust my post to account for this potential scenario.

**Comment by helrond** [comment]
So...given that piece of information, it also seems possible that there would be a single audio master file with multiple access files, right?

**Comment by jwts24** [comment]
@helrond No, if a master exists as one file, only one access file would be created. In the case given above, I should've noted that the seven-hour audio would've originally been recorded and organized as separate segments. There wouldn't be a case where the master file is rendered/stitched together. The patchwork would always occur when producing the access copy. So, the file count can be collapsed but shouldn't fan outward.

**Comment by helrond** [comment]
OK I think this is going to require a bit of a rethink of the validation logic, because there are three possible valid structures for audio:
- one master file, one access file
- multiple master files (distinguished by zero-padded suffixes such as `_01`), one access file (with `_r` suffix)
- multiple master files (distinguished by zero-padded suffixes such as `_01`), multiple access files (distinguished by zero-padded suffixes such as `_01` but without `_r`)

**Comment by helrond** [comment]
Documenting further conversations and updates to the digitization spec:
- We are dispensing with the `_a`, `_me`, `_ma` suffixes (this will need to be updated in other apps as well).
- In cases where there are multiple master files there will always only be a single access derivative file.

**Comment by helrond** [comment]
@jwts24 This should be resolved now. Give it a go and let me know what happens.

**Comment by jwts24** [comment]
@helrond Tested a package with multiple masters, with zero-padded suffixes but dropping the a/me/ma suffixes, and it passed.
